/**
 * Animation - Generated by PlayTUI
 * Frames: 14 @ 10 FPS
 */

export const animation = {
  name: "Animation",
  fps: 10,
  frames: [
    // Frame 0
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "column", alignItems: "flex-start", overflow: "hidden" }}>
      <ascii-font text="P" font="tiny" color="#4da8da" style={{ left: -4 }} />
    </box>,
    // Frame 1
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "column", alignItems: "flex-start", overflow: "hidden" }}>
      <ascii-font text="P" font="tiny" color="#4da8da" style={{ left: -4 }} />
    </box>,
    // Frame 2
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "row", alignItems: "flex-start", top: 0 }}>
      <box backgroundColor="#7bc0d4" style={{ width: 2, height: 2, flexDirection: "column", left: 0 }} />
      <ascii-font text="o" font="tiny" color="#4da8da" style={{ left: -2 }} />
    </box>,
    // Frame 3
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "row", alignItems: "flex-start", top: 0 }}>
      <box backgroundColor="#6bb0c4" style={{ width: 5, height: 2, flexDirection: "column", left: 6 }} />
      <ascii-font text="o" font="tiny" color="#4da8da" style={{ left: 6 }} />
    </box>,
    // Frame 4
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "row", alignItems: "flex-start", top: 0 }}>
      <box backgroundColor="#6bb0c4" style={{ width: 1, height: 2, flexDirection: "column", left: 11 }} />
      <ascii-font text="o" font="tiny" color="#4da8da" style={{ left: 11 }} />
    </box>,
    // Frame 5
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "row", alignItems: "flex-start", top: 0 }}>
      <box backgroundColor="#6bb0c4" visible={false} style={{ width: 1, height: 2, flexDirection: "column", left: 11 }} />
      <ascii-font text="o" font="tiny" color="#4da8da" style={{ left: 14 }} />
    </box>,
    // Frame 6
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "row", alignItems: "flex-start", top: 0 }}>
      <box backgroundColor="#6bb0c4" visible={false} style={{ width: 1, height: 2, flexDirection: "column", left: 11 }} />
      <ascii-font text="o" font="tiny" color="#4da8da" style={{ left: 15 }} />
    </box>,
    // Frame 7
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "row", alignItems: "flex-start", top: 0 }}>
      <box backgroundColor="#6bb0c4" visible={false} style={{ width: 1, height: 2, flexDirection: "column", left: 11 }} />
      <ascii-font text="o" font="tiny" color="#4da8da" style={{ left: 16 }} />
    </box>,
    // Frame 8
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "row", alignItems: "flex-start" }}>
      <box backgroundColor="#6bb0c4" visible={false} style={{ width: 1, height: 2, flexDirection: "column", left: 11 }} />
      <ascii-font text="o" font="tiny" color="#4da8da" style={{ left: 17 }} />
    </box>,
    // Frame 9
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "row", alignItems: "flex-start" }}>
      <box backgroundColor="#6bb0c4" visible={false} style={{ width: 1, height: 2, flexDirection: "column", left: 11 }} />
      <ascii-font text="o" font="tiny" color="#4da8da" style={{ left: 17 }} />
    </box>,
    // Frame 10
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "row", alignItems: "flex-start" }}>
      <box backgroundColor="#6bb0c4" visible={false} style={{ width: 1, height: 2, flexDirection: "column", left: 11 }} />
      <ascii-font text="o" font="tiny" color="#4da8da" style={{ left: 15 }} />
    </box>,
    // Frame 11
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "row", alignItems: "flex-start" }}>
      <box backgroundColor="#6bb0c4" style={{ width: 4, height: 2, flexDirection: "column", left: 9 }} />
      <ascii-font text="o" font="tiny" color="#4da8da" style={{ left: 2 }} />
    </box>,
    // Frame 12
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "row", alignItems: "flex-start", left: 0 }}>
      <box backgroundColor="#6bb0c4" style={{ width: 1, height: 2, flexDirection: "column", left: 5 }} />
      <ascii-font text="o" font="tiny" color="#4da8da" style={{ left: 1 }} />
    </box>,
    // Frame 13
      <box backgroundColor="#1c222c" style={{ width: 20, height: 2, flexDirection: "row", alignItems: "flex-start", left: 0 }}>
      <box backgroundColor="#6bb0c4" style={{ width: 2, height: 2, flexDirection: "column", left: 0 }} />
      <ascii-font text="o" font="tiny" color="#4da8da" visible={false} style={{ left: 0 }} />
    </box>
  ]
}
