/**
 * Animation - Generated by PlayTUI
 * Frames: 8 @ 10 FPS
 */

export const animation = {
  name: "Animation",
  fps: 10,
  frames: [
    // Frame 0
      <box shouldFill={false} backgroundColor="#4a5568" style={{ width: 16, height: "auto", flexDirection: "row", justifyContent: "center", alignItems: "center" }}>
      <box backgroundColor="#5bc0de" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1 }}>
        <text fg="#151a22"><strong>F1</strong></text>
      </box>
      <box backgroundColor="#4da8da" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1, overflow: "hidden", left: 0 }}>
        <text fg="#151a22"><strong>Edit</strong></text>
        <text fg="#d8dce5" style={{ left: 0, top: 0 }}>P</text>
        <text fg="#d8dce5" style={{ left: 1, top: -1 }}>l</text>
        <text fg="#d8dce5" style={{ left: 2, top: -2 }}>a</text>
        <text fg="#d8dce5" style={{ left: 3, top: -2 }}>y</text>
      </box>
    </box>,
    // Frame 1
      <box shouldFill={false} backgroundColor="#4a5568" style={{ width: 16, height: "auto", flexDirection: "row", justifyContent: "center", alignItems: "center" }}>
      <box backgroundColor="#5bc0de" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1 }}>
        <text fg="#151a22"><strong>F1</strong></text>
      </box>
      <box backgroundColor="#4da8da" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1, overflow: "hidden", left: 0 }}>
        <text fg="#151a22"><strong>Edit</strong></text>
        <text fg="#151a22" style={{ left: 0, top: 0 }}>P</text>
        <text fg="#d8dce5" style={{ left: 1, top: 0 }}>l</text>
        <text fg="#d8dce5" style={{ left: 2, top: -2 }}>a</text>
        <text fg="#d8dce5" style={{ left: 3, top: -2 }}>y</text>
      </box>
    </box>,
    // Frame 2
      <box shouldFill={false} backgroundColor="#4a5568" style={{ width: 16, height: "auto", flexDirection: "row", justifyContent: "center", alignItems: "center" }}>
      <box backgroundColor="#5bc0de" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1 }}>
        <text fg="#151a22"><strong>F1</strong></text>
      </box>
      <box backgroundColor="#4da8da" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1, overflow: "hidden", left: 0 }}>
        <text fg="#151a22"><strong>Edit</strong></text>
        <text fg="#151a22" style={{ left: 0, top: 0 }}><strong>P</strong></text>
        <text fg="#d8dce5" style={{ left: 1, top: 0 }}>l</text>
        <text fg="#d8dce5" style={{ left: 2, top: -1 }}>a</text>
        <text fg="#d8dce5" style={{ left: 3, top: 5 }}>y</text>
      </box>
    </box>,
    // Frame 3
      <box shouldFill={false} backgroundColor="#4a5568" style={{ width: 16, height: "auto", flexDirection: "row", justifyContent: "center", alignItems: "center" }}>
      <box backgroundColor="#5bc0de" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1 }}>
        <text fg="#151a22"><strong>F1</strong></text>
      </box>
      <box backgroundColor="#4da8da" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1, overflow: "hidden", left: 0 }}>
        <text fg="#151a22"><strong>Edit</strong></text>
        <text fg="#151a22" style={{ left: 0, top: 0 }}><strong>P</strong></text>
        <text fg="#151a22" style={{ left: 1, top: 0 }}>l</text>
        <text fg="#d8dce5" style={{ left: 2, top: -1 }}>a</text>
        <text fg="#d8dce5" style={{ left: 3, top: -1 }}>y</text>
      </box>
    </box>,
    // Frame 4
      <box shouldFill={false} backgroundColor="#4a5568" style={{ width: 16, height: "auto", flexDirection: "row", justifyContent: "center", alignItems: "center" }}>
      <box backgroundColor="#5bc0de" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1 }}>
        <text fg="#151a22"><strong>F1</strong></text>
      </box>
      <box backgroundColor="#4da8da" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1, overflow: "hidden", left: 0 }}>
        <text fg="#151a22"><strong>Edit</strong></text>
        <text fg="#151a22" style={{ left: 0, top: 0 }}><strong>P</strong></text>
        <text fg="#151a22" style={{ left: 1, top: 0 }}><strong>l</strong></text>
        <text fg="#d8dce5" style={{ left: 2, top: -1 }}>a</text>
        <text fg="#d8dce5" style={{ left: 3, top: -1 }}>y</text>
      </box>
    </box>,
    // Frame 5
      <box shouldFill={false} backgroundColor="#4a5568" style={{ width: 16, height: "auto", flexDirection: "row", justifyContent: "center", alignItems: "center" }}>
      <box backgroundColor="#5bc0de" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1 }}>
        <text fg="#151a22"><strong>F1</strong></text>
      </box>
      <box backgroundColor="#4da8da" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1, overflow: "hidden", left: 0 }}>
        <text fg="#151a22"><strong>Edit</strong></text>
        <text fg="#151a22" style={{ left: 0, top: 0 }}><strong>P</strong></text>
        <text fg="#151a22" style={{ left: 1, top: 0 }}><strong>l</strong></text>
        <text fg="#151a22" style={{ left: 2, top: -1 }}>a</text>
        <text fg="#d8dce5" style={{ left: 3, top: -1 }}>y</text>
      </box>
    </box>,
    // Frame 6
      <box shouldFill={false} backgroundColor="#4a5568" style={{ width: 16, height: "auto", flexDirection: "row", justifyContent: "center", alignItems: "center" }}>
      <box backgroundColor="#5bc0de" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1 }}>
        <text fg="#151a22"><strong>F1</strong></text>
      </box>
      <box backgroundColor="#4da8da" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1, overflow: "hidden", left: 0 }}>
        <text fg="#151a22"><strong>Edit</strong></text>
        <text fg="#151a22" style={{ left: 0, top: 0 }}><strong>P</strong></text>
        <text fg="#151a22" style={{ left: 1, top: 0 }}><strong>l</strong></text>
        <text fg="#151a22" style={{ left: 2, top: -1 }}><strong>a</strong></text>
        <text fg="#151a22" style={{ left: 3, top: -1 }}>y</text>
      </box>
    </box>,
    // Frame 7
      <box shouldFill={false} backgroundColor="#4a5568" style={{ width: 16, height: "auto", flexDirection: "row", justifyContent: "center", alignItems: "center" }}>
      <box backgroundColor="#5bc0de" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1 }}>
        <text fg="#151a22"><strong>F1</strong></text>
      </box>
      <box backgroundColor="#4da8da" style={{ width: "auto", height: 1, flexDirection: "column", alignItems: "flex-start", paddingRight: 1, paddingLeft: 1, overflow: "hidden", left: 0 }}>
        <text fg="#151a22"><strong>Edit</strong></text>
        <text fg="#151a22" style={{ left: 0, top: 0 }}><strong>P</strong></text>
        <text fg="#151a22" style={{ left: 1, top: 0 }}><strong>l</strong></text>
        <text fg="#151a22" style={{ left: 2, top: -1 }}><strong>a</strong></text>
        <text fg="#151a22" style={{ left: 3, top: -1 }}><strong>y</strong></text>
      </box>
    </box>
  ]
}
